---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
spec:
  tls:
    - hosts:
        - kibana.k8s.conatest.click
      secretName: ssl-certificate
  rules:
    - host: kibana.k8s.conatest.click
      http:
        paths:
        - path: /
          backend:
            serviceName: elastic-k8s-kb-http
            servicePort: 5601
