spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-microk8s
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              name: https
              protocol: TCP
            - containerPort: 5514
              hostPort: 5514
              name: syslog
              protocol: TCP
            - containerPort: 10254
              hostPort: 10254
              name: health
              protocol: TCP